### PR TITLE
Incorporates Quibilia's modifications to vanilla Rebirth

### PR DESCRIPTION
**Pull request by Fallenleader**
Quibilia's version is attempting to resolve the viewing issues and has
added further support to pokemon model formats resolving an older issue
I opened.
Unfortunately, the rendering changes broke Transfigured completely.

I took the format fixes and dae fixes and incorporated them into vanilla with his blessings.

The only changes are proper dae support, and the ability to import PB and PK files into material animations. Confirmed changes work as expected.

No other implementations or alterations. Other issues still persist.

### CODE REVIEW

**Comment by Quibilia** [comment]
The program works on my machine, but it appears to be broken beyond repair in the field. Hopefully I can get the program working after the next Rebirth commit.

**Comment by Quibilia** [comment]
Changes committed. Go, go, go!

**Comment by Fallenleader** [comment]
@Quibilia I need to push those changes and cancel this pull request. mind mentioning the altered code? I would suggest forking the changes I made from my git, add in your fixes and submit a pull request to @gdkchan  
your changes won't directly affect this pull request.

**Comment by gdkchan** [comment]
Unfortunately I can't merge this, sorry. I took a look at Quibilia's changes on DAE exporter, and he is checking for specific material names on Pokémon to determine which textures to export (?), which isn't good becuase this tool aims to support various games, so game-specific hacks does no good. There's also a lot of boilerplate copy-paste added code in there that is unecessary (the class grew by around 800 lines due to this). Also, the added classes for PB, PF and PK seems to read the container structure in a hacky way. I already made a class to read those XX container formats from Pokémon [here](https://github.com/gdkchan/Ohana3DS-Rebirth/blob/master/Ohana3DS%20Rebirth/Ohana/Containers/PkmnContainer.cs), all of them seems to have this same structure:

2 bytes = Signature, 2 ASCII upper case characters
2 bytes = Section count
Then, for n = 0 To Section count:
4 bytes = Address of the section
At the end, it have the total size of the file that also uses 4 bytes, to, to calculate the length of a section, you can just do nextOffset - offset.

I think that the best option here is you keeping your repo with your hacks that are specific to Pokémon. I don't want to sound rude and I do appreciate your help. I'll leave this open for discussions.

**Comment by Quibilia** [comment]
@gdkchan I understand completely. Godspeed, Transfigured!

**Comment by Fallenleader** [comment]
yea, I actually realized I DIDN't fix the DAE part, and cannot get this dang request to close.
I DO know that PB and PK is still unsuported in rebirth, so hacky or not, I will keep the changes in my variation since it simply works and does fix that lack of support issue. If you can cancel this request, please do.

**Comment by Fallenleader** [comment]
Please note I meant no offense in my comment. I was typing it in a hurry because I had to leave and it kinda came out blunt and rude.

**Pull request closed without merging**
